### ISSUE TITLE
clipping heard when a sound is cut off by another sound

### ISSUE THREAD

**Issue by avi-0** [TheArcadion/tm-action-key-piano#2]
you can hear a clicky sound when you play two notes in sequence, this is likely because when the first note is cut off, it goes to 0 volume instantly (it needs a small release time to avoid that)

**Comment by TheArcadion** [comment]
I am looking into it. I tried out a few fade out methods, but it does lower the amount of notes per second you can play. It seems the TM Audio API is not really optimized for fast audio changes.

**Comment by TheArcadion** [comment]
I settled on fading out while the next note is playing. As some people switch action keys quite rapidly, limiting the amount of notes might hinder the usability, or at least make the plugin more inconsistent.

If you have any more feedback, feel free to let me know! I will release an update soon, with the fix included.

**Comment by avi-0** [comment]
nice! if anything, i'd also like to be able to utilize the full range of keys (c#, d# etc) but that's no biggie :)

**Comment by TheArcadion** [comment]
Heheheh, I've been putting it off as it's boring Audacity work, but now I know that there's demand for it, I'll get it done.

For completeness I will be putting both sharps and flats in (however C# will be the same as Db). This ensures that chords can be written correctly, and both the lowest and highest notes (C1 and C4) have their sharps and flats. Otherwise this might exclude chords in the lower or higher octaves.

Is this at least similar to what you had in mind?

**Comment by avi-0** [comment]
hmm can you not just play a single sample (or just a few, say C1, C2, C3) transposed to the necessary pitches?

I was thinking of just sharps, it's what you often see in daws and music trackers by default

**Comment by TheArcadion** [comment]
Usually that works, yes, but I haven't found any support in the openplanet docs for such operations. If you have more knowledge of this matter, feel free to let me know :p

Sharps only is okay! ~~I'll just leave out the lower Cb1 then, or just have than one as the exception?~~

Edit: Just started work on the preparation of the audio files, when I noticed there is no such thing as Cb1 :p (Well, there is, but that's a technicality).
